/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as ApiPublicDailyRollupRouteImport } from './routes/api/public/daily-rollup'
import { Route as ApiPublicRunScansRouteImport } from './routes/api/public/run-scans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDailyRollupRoute = ApiPublicDailyRollupRouteImport.update({
  id: '/api/public/daily-rollup',
  path: '/api/public/daily-rollup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunScansRoute = ApiPublicRunScansRouteImport.update({
  id: '/api/public/run-scans',
  path: '/api/public/run-scans',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/api/public/daily-rollup': typeof ApiPublicDailyRollupRoute
  '/api/public/run-scans': typeof ApiPublicRunScansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/api/public/daily-rollup': typeof ApiPublicDailyRollupRoute
  '/api/public/run-scans': typeof ApiPublicRunScansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/api/public/daily-rollup': typeof ApiPublicDailyRollupRoute
  '/api/public/run-scans': typeof ApiPublicRunScansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/proposals'
    | '/api/public/daily-rollup'
    | '/api/public/run-scans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/proposals'
    | '/api/public/daily-rollup'
    | '/api/public/run-scans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/proposals'
    | '/api/public/daily-rollup'
    | '/api/public/run-scans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicDailyRollupRoute: typeof ApiPublicDailyRollupRoute
  ApiPublicRunScansRoute: typeof ApiPublicRunScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/daily-rollup': {
      id: '/api/public/daily-rollup'
      path: '/api/public/daily-rollup'
      fullPath: '/api/public/daily-rollup'
      preLoaderRoute: typeof ApiPublicDailyRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-scans': {
      id: '/api/public/run-scans'
      path: '/api/public/run-scans'
      fullPath: '/api/public/run-scans'
      preLoaderRoute: typeof ApiPublicRunScansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicDailyRollupRoute: ApiPublicDailyRollupRoute,
  ApiPublicRunScansRoute: ApiPublicRunScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
